import lessonPlanData from "@/services/mockData/lessonPlans.json";

let lessonPlans = [...lessonPlanData];

// Default categories for lesson plans
let categories = [
  { Id: 1, name: "Core Subjects", description: "Essential academic subjects" },
  { Id: 2, name: "Arts & Creativity", description: "Creative and artistic subjects" },
  { Id: 3, name: "Physical Education", description: "Sports and physical activities" },
  { Id: 4, name: "Language Arts", description: "Communication and literature" },
  { Id: 5, name: "STEM", description: "Science, Technology, Engineering, Math" }
];

// Default icons mapping for different subjects and class levels
const defaultIconsMap = {
  'Mathematics': {
    '1A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggMTFoOHYySDh2LTJaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMSA4aDJ2OGgtMlY4WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '1B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggMTFoOHYySDh2LTJaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMSA4aDJ2OGgtMlY4WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '2A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjE4IiBoZWlnaHQ9IjE4IiB4PSIzIiB5PSIzIiByeD0iMiIgZmlsbD0iIzRBOTBFMiIvPgo8cGF0aCBkPSJNOSA5aDZhMyAzIDAgMCAxIDAgNmgtNmEzIDMgMCAwIDEgMC02WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '2B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjE4IiBoZWlnaHQ9IjE4IiB4PSIzIiB5PSIzIiByeD0iMiIgZmlsbD0iIzRBOTBFMiIvPgo8cGF0aCBkPSJNOSA5aDZhMyAzIDAgMCAxIDAgNmgtNmEzIDMgMCAwIDEgMC02WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '3A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEwIDJIMTRWMjJIMTBWMlpNMTYgOEwyMiAxNEgxNlY4WiIgZmlsbD0iIzRBOTBFMiIvPgo8cGF0aCBkPSJNMiA4SDhWMTRIMlY4WiIgZmlsbD0iIzRBOTBFMiIvPgo8L3N2Zz4=',
    '3B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEwIDJIMTRWMjJIMTBWMlpNMTYgOEwyMiAxNEgxNlY4WiIgZmlsbD0iIzRBOTBFMiIvPgo8cGF0aCBkPSJNMiA4SDhWMTRIMlY4WiIgZmlsbD0iIzRBOTBFMiIvPgo8L3N2Zz4=',
    '4A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEwIDJIMTRWMjJIMTBWMlpNMTYgOEwyMiAxNEgxNlY4WiIgZmlsbD0iIzRBOTBFMiIvPgo8cGF0aCBkPSJNMiA4SDhWMTRIMlY4WiIgZmlsbD0iIzRBOTBFMiIvPgo8L3N2Zz4=',
    '4B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEwIDJIMTRWMjJIMTBWMlpNMTYgOEwyMiAxNEgxNlY4WiIgZmlsbD0iIzRBOTBFMiIvPgo8cGF0aCBkPSJNMiA4SDhWMTRIMlY4WiIgZmlsbD0iIzRBOTBFMiIvPgo8L3N2Zz4=',
    '5A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJDMTcuNSAyIDIyIDYuNSAyMiAxMlMxNy41IDIyIDEyIDIyIDIgMTcuNSAyIDEyIDYuNSAyIDEyIDJaIiBmaWxsPSIjNEE5MEUyIi8+CjxwYXRoIGQ9Ik0xMCA4aDR2OGgtNFY4WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '5B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJDMTcuNSAyIDIyIDYuNSAyMiAxMlMxNy41IDIyIDEyIDIyIDIgMTcuNSAyIDEyIDYuNSAyIDEyIDJaIiBmaWxsPSIjNEE5MEUyIi8+CjxwYXRoIGQ9Ik0xMCA4aDR2OGgtNFY4WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4='
  },
  'English': {
    '1A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTQgM0gyMEMxOS41IDMgMTkgMy41IDE5IDRWMjBDMTkgMjAuNSAxOC41IDIxIDE4IDIxSDZDNS41IDIxIDUgMjAuNSA1IDIwVjRDNSAzLjUgNC41IDMgNCAzWiIgZmlsbD0iIzdFRDMyMSIvPgo8cGF0aCBkPSJNNyA3SDEyVjlIN1Y3WiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxMUgxN1YxM0g3VjExWiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxNUgxNVYxN0g3VjE1WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '1B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTQgM0gyMEMxOS41IDMgMTkgMy41IDE5IDRWMjBDMTkgMjAuNSAxOC41IDIxIDE4IDIxSDZDNS41IDIxIDUgMjAuNSA1IDIwVjRDNSAzLjUgNC41IDMgNCAzWiIgZmlsbD0iIzdFRDMyMSIvPgo8cGF0aCBkPSJNNyA3SDEyVjlIN1Y3WiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxMUgxN1YxM0g3VjExWiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxNUgxNVYxN0g3VjE1WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '2A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTQgM0gyMEMxOS41IDMgMTkgMy41IDE5IDRWMjBDMTkgMjAuNSAxOC41IDIxIDE4IDIxSDZDNS41IDIxIDUgMjAuNSA1IDIwVjRDNSAzLjUgNC41IDMgNCAzWiIgZmlsbD0iIzZEQzI5MSIvPgo8cGF0aCBkPSJNNyA3SDEyVjlIN1Y3WiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxMUgxN1YxM0g3VjExWiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxNUgxNVYxN0g3VjE1WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '2B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTQgM0gyMEMxOS41IDMgMTkgMy41IDE5IDRWMjBDMTkgMjAuNSAxOC41IDIxIDE4IDIxSDZDNS41IDIxIDUgMjAuNSA1IDIwVjRDNSAzLjUgNC41IDMgNCAzWiIgZmlsbD0iIzZEQzI5MSIvPgo8cGF0aCBkPSJNNyA3SDEyVjlIN1Y3WiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxMUgxN1YxM0g3VjExWiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxNUgxNVYxN0g3VjE1WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '3A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTQgM0gyMEMxOS41IDMgMTkgMy41IDE5IDRWMjBDMTkgMjAuNSAxOC41IDIxIDE4IDIxSDZDNS41IDIxIDUgMjAuNSA1IDIwVjRDNSAzLjUgNC41IDMgNCAzWiIgZmlsbD0iIzJEQzY1MyIvPgo8cGF0aCBkPSJNNyA3SDEyVjlIN1Y3WiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxMUgxN1YxM0g3VjExWiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxNUgxNVYxN0g3VjE1WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '3B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTQgM0gyMEMxOS41IDMgMTkgMy41IDE5IDRWMjBDMTkgMjAuNSAxOC41IDIxIDE4IDIxSDZDNS41IDIxIDUgMjAuNSA1IDIwVjRDNSAzLjUgNC41IDMgNCAzWiIgZmlsbD0iIzJEQzY1MyIvPgo8cGF0aCBkPSJNNyA3SDEyVjlIN1Y3WiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxMUgxN1YxM0g3VjExWiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxNUgxNVYxN0g3VjE1WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '4A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTQgM0gyMEMxOS41IDMgMTkgMy41IDE5IDRWMjBDMTkgMjAuNSAxOC41IDIxIDE4IDIxSDZDNS41IDIxIDUgMjAuNSA1IDIwVjRDNSAzLjUgNC41IDMgNCAzWiIgZmlsbD0iIzdFRDMyMSIvPgo8cGF0aCBkPSJNNyA3SDEyVjlIN1Y3WiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxMUgxN1YxM0g3VjExWiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxNUgxNVYxN0g3VjE1WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '4B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTQgM0gyMEMxOS41IDMgMTkgMy41IDE5IDRWMjBDMTkgMjAuNSAxOC41IDIxIDE4IDIxSDZDNS41IDIxIDUgMjAuNSA1IDIwVjRDNSAzLjUgNC41IDMgNCAzWiIgZmlsbD0iIzdFRDMyMSIvPgo8cGF0aCBkPSJNNyA3SDEyVjlIN1Y3WiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxMUgxN1YxM0g3VjExWiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxNUgxNVYxN0g3VjE1WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '5A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTQgM0gyMEMxOS41IDMgMTkgMy41IDE5IDRWMjBDMTkgMjAuNSAxOC41IDIxIDE4IDIxSDZDNS41IDIxIDUgMjAuNSA1IDIwVjRDNSAzLjUgNC41IDMgNCAzWiIgZmlsbD0iIzEzN0ZCOCIvPgo8cGF0aCBkPSJNNyA3SDEyVjlIN1Y3WiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxMUgxN1YxM0g3VjExWiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxNUgxNVYxN0g3VjE1WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4=',
    '5B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTQgM0gyMEMxOS41IDMgMTkgMy41IDE5IDRWMjBDMTkgMjAuNSAxOC41IDIxIDE4IDIxSDZDNS41IDIxIDUgMjAuNSA1IDIwVjRDNSAzLjUgNC41IDMgNCAzWiIgZmlsbD0iIzEzN0ZCOCIvPgo8cGF0aCBkPSJNNyA3SDEyVjlIN1Y3WiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxMUgxN1YxM0g3VjExWiIgZmlsbD0iI0ZGRkZGRiIvPgo8cGF0aCBkPSJNNyAxNUgxNVYxN0g3VjE1WiIgZmlsbD0iI0ZGRkZGRiIvPgo8L3N2Zz4='
  },
  'Science': {
    '1A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTUgN0g5TDEyIDJaIiBmaWxsPSIjNEE5MEUyIi8+CjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjgiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggMTZDOCAxNiAxMCAxOCAxMiAxOEMxNCAxOCAxNiAxNiAxNiAxNiIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPC9zdmc+',
    '1B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTUgN0g5TDEyIDJaIiBmaWxsPSIjNEE5MEUyIi8+CjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjgiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggMTZDOCAxNiAxMCAxOCAxMiAxOEMxNCAxOCAxNiAxNiAxNiAxNiIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPC9zdmc+',
    '2A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTUgN0g5TDEyIDJaIiBmaWxsPSIjNkQ5NEVCIi8+CjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjgiIGZpbGw9IiM2RDk0RUIiLz4KPHBhdGggZD0iTTggMTZDOCAxNiAxMCAxOCAxMiAxOEMxNCAxOCAxNiAxNiAxNiAxNiIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPC9zdmc+',
    '2B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTUgN0g5TDEyIDJaIiBmaWxsPSIjNkQ5NEVCIi8+CjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjgiIGZpbGw9IiM2RDk0RUIiLz4KPHBhdGggZD0iTTggMTZDOCAxNiAxMCAxOCAxMiAxOEMxNCAxOCAxNiAxNiAxNiAxNiIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPC9zdmc+',
    '3A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTUgN0g5TDEyIDJaIiBmaWxsPSIjNEE5MEUyIi8+CjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjgiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggMTZDOCAxNiAxMCAxOCAxMiAxOEMxNCAxOCAxNiAxNiAxNiAxNiIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPC9zdmc+',
    '3B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTUgN0g5TDEyIDJaIiBmaWxsPSIjNEE5MEUyIi8+CjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjgiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggMTZDOCAxNiAxMCAxOCAxMiAxOEMxNCAxOCAxNiAxNiAxNiAxNiIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPC9zdmc+',
    '4A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTUgN0g5TDEyIDJaIiBmaWxsPSIjNEE5MEUyIi8+CjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjgiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggMTZDOCAxNiAxMCAxOCAxMiAxOEMxNCAxOCAxNiAxNiAxNiAxNiIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPC9zdmc+',
    '4B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTUgN0g5TDEyIDJaIiBmaWxsPSIjNEE5MEUyIi8+CjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjgiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggMTZDOCAxNiAxMCAxOCAxMiAxOEMxNCAxOCAxNiAxNiAxNiAxNiIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPC9zdmc+',
    '5A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTUgN0g5TDEyIDJaIiBmaWxsPSIjMkQ0NkYzIi8+CjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjgiIGZpbGw9IiMyRDQ2RjMiLz4KPHBhdGggZD0iTTggMTZDOCAxNiAxMCAxOCAxMiAxOEMxNCAxOCAxNiAxNiAxNiAxNiIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPC9zdmc+',
    '5B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTUgN0g5TDEyIDJaIiBmaWxsPSIjMkQ0NkYzIi8+CjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjgiIGZpbGw9IiMyRDQ2RjMiLz4KPHBhdGggZD0iTTggMTZDOCAxNiAxMCAxOCAxMiAxOEMxNCAxOCAxNiAxNiAxNiAxNiIgc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPC9zdmc+'
  },
  'History': {
    '1A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTQgMTBIMjJMMTYgMTZMMTggMjRMMTIgMjBMNiAyNEw4IDE2TDIgMTBIMTBMMTIgMloiIGZpbGw9IiNGNUE2MjMiLz4KPHBhdGggZD0iTTEyIDZMMTMgMTBIMTdMMTQgMTNMMTUgMTdMMTIgMTVMOSAxN0wxMCAxM0w3IDEwSDExTDEyIDZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '1B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTQgMTBIMjJMMTYgMTZMMTggMjRMMTIgMjBMNiAyNEw4IDE2TDIgMTBIMTBMMTIgMloiIGZpbGw9IiNGNUE2MjMiLz4KPHBhdGggZD0iTTEyIDZMMTMgMTBIMTdMMTQgMTNMMTUgMTdMMTIgMTVMOSAxN0wxMCAxM0w3IDEwSDExTDEyIDZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '2A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTQgMTBIMjJMMTYgMTZMMTggMjRMMTIgMjBMNiAyNEw4IDE2TDIgMTBIMTBMMTIgMloiIGZpbGw9IiNGNUE2MjMiLz4KPHBhdGggZD0iTTEyIDZMMTMgMTBIMTdMMTQgMTNMMTUgMTdMMTIgMTVMOSAxN0wxMCAxM0w3IDEwSDExTDEyIDZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '2B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTQgMTBIMjJMMTYgMTZMMTggMjRMMTIgMjBMNiAyNEw4IDE2TDIgMTBIMTBMMTIgMloiIGZpbGw9IiNGNUE2MjMiLz4KPHBhdGggZD0iTTEyIDZMMTMgMTBIMTdMMTQgMTNMMTUgMTdMMTIgMTVMOSAxN0wxMCAxM0w3IDEwSDExTDEyIDZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '3A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTQgMTBIMjJMMTYgMTZMMTggMjRMMTIgMjBMNiAyNEw4IDE2TDIgMTBIMTBMMTIgMloiIGZpbGw9IiNGNUE2MjMiLz4KPHBhdGggZD0iTTEyIDZMMTMgMTBIMTdMMTQgMTNMMTUgMTdMMTIgMTVMOSAxN0wxMCAxM0w3IDEwSDExTDEyIDZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '3B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTQgMTBIMjJMMTYgMTZMMTggMjRMMTIgMjBMNiAyNEw4IDE2TDIgMTBIMTBMMTIgMloiIGZpbGw9IiNGNUE2MjMiLz4KPHBhdGggZD0iTTEyIDZMMTMgMTBIMTdMMTQgMTNMMTUgMTdMMTIgMTVMOSAxN0wxMCAxM0w3IDEwSDExTDEyIDZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '4A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTQgMTBIMjJMMTYgMTZMMTggMjRMMTIgMjBMNiAyNEw4IDE2TDIgMTBIMTBMMTIgMloiIGZpbGw9IiNGNUE2MjMiLz4KPHBhdGggZD0iTTEyIDZMMTMgMTBIMTdMMTQgMTNMMTUgMTdMMTIgMTVMOSAxN0wxMCAxM0w3IDEwSDExTDEyIDZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '4B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTQgMTBIMjJMMTYgMTZMMTggMjRMMTIgMjBMNiAyNEw4IDE2TDIgMTBIMTBMMTIgMloiIGZpbGw9IiNGNUE2MjMiLz4KPHBhdGggZD0iTTEyIDZMMTMgMTBIMTdMMTQgMTNMMTUgMTdMMTIgMTVMOSAxN0wxMCAxM0w3IDEwSDExTDEyIDZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '5A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTQgMTBIMjJMMTYgMTZMMTggMjRMMTIgMjBMNiAyNEw4IDE2TDIgMTBIMTBMMTIgMloiIGZpbGw9IiNEOTlDMDAiLz4KPHBhdGggZD0iTTEyIDZMMTMgMTBIMTdMMTQgMTNMMTUgMTdMMTIgMTVMOSAxN0wxMCAxM0w3IDEwSDExTDEyIDZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '5B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTQgMTBIMjJMMTYgMTZMMTggMjRMMTIgMjBMNiAyNEw4IDE2TDIgMTBIMTBMMTIgMloiIGZpbGw9IiNEOTlDMDAiLz4KPHBhdGggZD0iTTEyIDZMMTMgMTBIMTdMMTQgMTNMMTUgMTdMMTIgMTVMOSAxN0wxMCAxM0w3IDEwSDExTDEyIDZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg=='
  },
  'Geography': {
    '1A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggNmg4djJIOHYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTEwIDEwaDR2NEgxMHYtNFoiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTYgMTZoMTJ2MkgxNnYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPC9zdmc+',
    '1B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggNmg4djJIOHYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTEwIDEwaDR2NEgxMHYtNFoiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTYgMTZoMTJ2MkgxNnYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPC9zdmc+',
    '2A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggNmg4djJIOHYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTEwIDEwaDR2NEgxMHYtNFoiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTYgMTZoMTJ2MkgxNnYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPC9zdmc+',
    '2B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggNmg4djJIOHYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTEwIDEwaDR2NEgxMHYtNFoiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTYgMTZoMTJ2MkgxNnYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPC9zdmc+',
    '3A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggNmg4djJIOHYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTEwIDEwaDR2NEgxMHYtNFoiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTYgMTZoMTJ2MkgxNnYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPC9zdmc+',
    '3B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggNmg4djJIOHYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTEwIDEwaDR2NEgxMHYtNFoiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTYgMTZoMTJ2MkgxNnYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPC9zdmc+',
    '4A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggNmg4djJIOHYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTEwIDEwaDR2NEgxMHYtNFoiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTYgMTZoMTJ2MkgxNnYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPC9zdmc+',
    '4B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTggNmg4djJIOHYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTEwIDEwaDR2NEgxMHYtNFoiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTYgMTZoMTJ2MkgxNnYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPC9zdmc+',
    '5A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiMxNjU5NEEiLz4KPHBhdGggZD0iTTggNmg4djJIOHYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTEwIDEwaDR2NEgxMHYtNFoiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTYgMTZoMTJ2MkgxNnYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPC9zdmc+',
    '5B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiMxNjU5NEEiLz4KPHBhdGggZD0iTTggNmg4djJIOHYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTEwIDEwaDR2NEgxMHYtNFoiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTYgMTZoMTJ2MkgxNnYtMloiIGZpbGw9IiM3RUQzMjEiLz4KPC9zdmc+'
  },
  'Art': {
    '1A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTggMTBIMTBMMTIgMloiIGZpbGw9IiNEMDAyMUIiLz4KPHBhdGggZD0iTTYgMTBIMTRMMTIgMThMNiAxMFoiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTE0IDEwSDIyTDIwIDE4TDE0IDEwWiIgZmlsbD0iI0Y1QTYyMyIvPgo8L3N2Zz4=',
    '1B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTggMTBIMTBMMTIgMloiIGZpbGw9IiNEMDAyMUIiLz4KPHBhdGggZD0iTTYgMTBIMTRMMTIgMThMNiAxMFoiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTE0IDEwSDIyTDIwIDE4TDE0IDEwWiIgZmlsbD0iI0Y1QTYyMyIvPgo8L3N2Zz4=',
    '2A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTggMTBIMTBMMTIgMloiIGZpbGw9IiNEMDAyMUIiLz4KPHBhdGggZD0iTTYgMTBIMTRMMTIgMThMNiAxMFoiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTE0IDEwSDIyTDIwIDE4TDE0IDEwWiIgZmlsbD0iI0Y1QTYyMyIvPgo8L3N2Zz4=',
    '2B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTggMTBIMTBMMTIgMloiIGZpbGw9IiNEMDAyMUIiLz4KPHBhdGggZD0iTTYgMTBIMTRMMTIgMThMNiAxMFoiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTE0IDEwSDIyTDIwIDE4TDE0IDEwWiIgZmlsbD0iI0Y1QTYyMyIvPgo8L3N2Zz4=',
    '3A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTggMTBIMTBMMTIgMloiIGZpbGw9IiNEMDAyMUIiLz4KPHBhdGggZD0iTTYgMTBIMTRMMTIgMThMNiAxMFoiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTE0IDEwSDIyTDIwIDE4TDE0IDEwWiIgZmlsbD0iI0Y1QTYyMyIvPgo8L3N2Zz4=',
    '3B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTggMTBIMTBMMTIgMloiIGZpbGw9IiNEMDAyMUIiLz4KPHBhdGggZD0iTTYgMTBIMTRMMTIgMThMNiAxMFoiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTE0IDEwSDIyTDIwIDE4TDE0IDEwWiIgZmlsbD0iI0Y1QTYyMyIvPgo8L3N2Zz4=',
    '4A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTggMTBIMTBMMTIgMloiIGZpbGw9IiNEMDAyMUIiLz4KPHBhdGggZD0iTTYgMTBIMTRMMTIgMThMNiAxMFoiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTE0IDEwSDIyTDIwIDE4TDE0IDEwWiIgZmlsbD0iI0Y1QTYyMyIvPgo8L3N2Zz4=',
    '4B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTggMTBIMTBMMTIgMloiIGZpbGw9IiNEMDAyMUIiLz4KPHBhdGggZD0iTTYgMTBIMTRMMTIgMThMNiAxMFoiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTE0IDEwSDIyTDIwIDE4TDE0IDEwWiIgZmlsbD0iI0Y1QTYyMyIvPgo8L3N2Zz4=',
    '5A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTggMTBIMTBMMTIgMloiIGZpbGw9IiNEMDAyMUIiLz4KPHBhdGggZD0iTTYgMTBIMTRMMTIgMThMNiAxMFoiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTE0IDEwSDIyTDIwIDE4TDE0IDEwWiIgZmlsbD0iI0Y1QTYyMyIvPgo8L3N2Zz4=',
    '5B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMTggMTBIMTBMMTIgMloiIGZpbGw9IiNEMDAyMUIiLz4KPHBhdGggZD0iTTYgMTBIMTRMMTIgMThMNiAxMFoiIGZpbGw9IiM0QTkwRTIiLz4KPHBhdGggZD0iTTE0IDEwSDIyTDIwIDE4TDE0IDEwWiIgZmlsbD0iI0Y1QTYyMyIvPgo8L3N2Zz4='
  },
  'Physical Education': {
    '1A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTggOEgxNlYxNkg4VjhaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMCA2SDE0VjE4SDEwVjZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '1B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTggOEgxNlYxNkg4VjhaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMCA2SDE0VjE4SDEwVjZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '2A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTggOEgxNlYxNkg4VjhaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMCA2SDE0VjE4SDEwVjZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '2B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTggOEgxNlYxNkg4VjhaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMCA2SDE0VjE4SDEwVjZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '3A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTggOEgxNlYxNkg4VjhaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMCA2SDE0VjE4SDEwVjZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '3B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTggOEgxNlYxNkg4VjhaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMCA2SDE0VjE4SDEwVjZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '4A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTggOEgxNlYxNkg4VjhaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMCA2SDE0VjE4SDEwVjZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '4B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM3RUQzMjEiLz4KPHBhdGggZD0iTTggOEgxNlYxNkg4VjhaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMCA2SDE0VjE4SDEwVjZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '5A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiMzNjhBM0IiLz4KPHBhdGggZD0iTTggOEgxNlYxNkg4VjhaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMCA2SDE0VjE4SDEwVjZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '5B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiMzNjhBM0IiLz4KPHBhdGggZD0iTTggOEgxNlYxNkg4VjhaIiBmaWxsPSIjRkZGRkZGIi8+CjxwYXRoIGQ9Ik0xMCA2SDE0VjE4SDEwVjZaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg=='
  },
  'Music': {
    '1A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM5NTMzRkYiLz4KPHBhdGggZD0iTTkgOXY2YTIgMiAwIDEgMCAzIDAgMiAyIDAgMCAwIDMgMFY5cS0xIDEtMy0xVjlxLTEgMS0zLTFaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '1B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM5NTMzRkYiLz4KPHBhdGggZD0iTTkgOXY2YTIgMiAwIDEgMCAzIDAgMiAyIDAgMCAwIDMgMFY5cS0xIDEtMy0xVjlxLTEgMS0zLTFaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '2A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM5NTMzRkYiLz4KPHBhdGggZD0iTTkgOXY2YTIgMiAwIDEgMCAzIDAgMiAyIDAgMCAwIDMgMFY5cS0xIDEtMy0xVjlxLTEgMS0zLTFaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '2B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM5NTMzRkYiLz4KPHBhdGggZD0iTTkgOXY2YTIgMiAwIDEgMCAzIDAgMiAyIDAgMCAwIDMgMFY5cS0xIDEtMy0xVjlxLTEgMS0zLTFaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '3A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM5NTMzRkYiLz4KPHBhdGggZD0iTTkgOXY2YTIgMiAwIDEgMCAzIDAgMiAyIDAgMCAwIDMgMFY5cS0xIDEtMy0xVjlxLTEgMS0zLTFaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '3B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM5NTMzRkYiLz4KPHBhdGggZD0iTTkgOXY2YTIgMiAwIDEgMCAzIDAgMiAyIDAgMCAwIDMgMFY5cS0xIDEtMy0xVjlxLTEgMS0zLTFaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '4A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM5NTMzRkYiLz4KPHBhdGggZD0iTTkgOXY2YTIgMiAwIDEgMCAzIDAgMiAyIDAgMCAwIDMgMFY5cS0xIDEtMy0xVjlxLTEgMS0zLTFaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '4B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM5NTMzRkYiLz4KPHBhdGggZD0iTTkgOXY2YTIgMiAwIDEgMCAzIDAgMiAyIDAgMCAwIDMgMFY5cS0xIDEtMy0xVjlxLTEgMS0zLTFaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '5A': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM1QjIxQjYiLz4KPHBhdGggZD0iTTkgOXY2YTIgMiAwIDEgMCAzIDAgMiAyIDAgMCAwIDMgMFY5cS0xIDEtMy0xVjlxLTEgMS0zLTFaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg==',
    '5B': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIGZpbGw9IiM1QjIxQjYiLz4KPHBhdGggZD0iTTkgOXY2YTIgMiAwIDEgMCAzIDAgMiAyIDAgMCAwIDMgMFY5cS0xIDEtMy0xVjlxLTEgMS0zLTFaIiBmaWxsPSIjRkZGRkZGIi8+Cjwvc3ZnPg=='
  }
};

const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

export const lessonPlanService = {
  async getAll() {
    await delay(300);
    return [...lessonPlans];
  },

  async getById(id) {
    await delay(200);
    const lessonPlan = lessonPlans.find(lp => lp.Id === parseInt(id));
    if (!lessonPlan) {
      throw new Error("Lesson plan not found");
    }
    return { ...lessonPlan };
  },

  async create(lessonPlanData) {
    await delay(400);
    const newLessonPlan = {
      ...lessonPlanData,
      Id: Math.max(...lessonPlans.map(lp => lp.Id), 0) + 1
    };
    lessonPlans.push(newLessonPlan);
    return { ...newLessonPlan };
  },

  async update(id, lessonPlanData) {
    await delay(300);
    const index = lessonPlans.findIndex(lp => lp.Id === parseInt(id));
    if (index === -1) {
      throw new Error("Lesson plan not found");
    }
    lessonPlans[index] = { ...lessonPlans[index], ...lessonPlanData };
    return { ...lessonPlans[index] };
  },

  async delete(id) {
    await delay(200);
    const index = lessonPlans.findIndex(lp => lp.Id === parseInt(id));
    if (index === -1) {
      throw new Error("Lesson plan not found");
    }
    lessonPlans.splice(index, 1);
    return true;
  },

  // Category management
  async getCategories() {
    await delay(200);
    return [...categories];
  },

  async updateCategory(id, categoryData) {
    await delay(300);
    const index = categories.findIndex(cat => cat.Id === parseInt(id));
    if (index === -1) {
      throw new Error("Category not found");
    }
    categories[index] = { ...categories[index], ...categoryData };
    return { ...categories[index] };
  },

  async deleteCategory(id) {
    await delay(200);
    const index = categories.findIndex(cat => cat.Id === parseInt(id));
    if (index === -1) {
      throw new Error("Category not found");
    }
    categories.splice(index, 1);
    return true;
  },

  // Bulk operations
  async updateMultiple(ids, updateData) {
    await delay(400);
    const updatedPlans = [];
    for (const id of ids) {
      const index = lessonPlans.findIndex(lp => lp.Id === parseInt(id));
      if (index !== -1) {
        lessonPlans[index] = { ...lessonPlans[index], ...updateData };
        updatedPlans.push({ ...lessonPlans[index] });
      }
    }
    return updatedPlans;
  },

  async deleteMultiple(ids) {
    await delay(300);
    const deletedIds = [];
    for (const id of ids) {
      const index = lessonPlans.findIndex(lp => lp.Id === parseInt(id));
      if (index !== -1) {
        lessonPlans.splice(index, 1);
        deletedIds.push(parseInt(id));
      }
    }
return deletedIds;
  },

  // Individual export methods
  async exportSinglePDF(id) {
    await delay(200);
    const lessonPlan = lessonPlans.find(lp => lp.Id === parseInt(id));
    if (!lessonPlan) {
      throw new Error("Lesson plan not found");
    }
    return { ...lessonPlan };
  },

  async exportSingleDOCX(id) {
    await delay(200);
    const lessonPlan = lessonPlans.find(lp => lp.Id === parseInt(id));
    if (!lessonPlan) {
      throw new Error("Lesson plan not found");
    }
    return { ...lessonPlan };
  },

  async shareLessonPlan(id) {
    await delay(200);
    const lessonPlan = lessonPlans.find(lp => lp.Id === parseInt(id));
    if (!lessonPlan) {
      throw new Error("Lesson plan not found");
    }
return { ...lessonPlan };
  },

  // Get default icon for subject and class level
  async getDefaultIcon(subject, className) {
    await delay(150);
    
    if (!subject || !className) {
      return null;
    }
    
    const subjectMappings = defaultIconsMap[subject];
    if (!subjectMappings) {
      return null;
    }
    
    const icon = subjectMappings[className];
    return icon || null;
  },

  // Get all available default icons for a subject
  async getSubjectIcons(subject) {
    await delay(150);
    
    if (!subject) {
      return {};
    }
    
    return defaultIconsMap[subject] || {};
  },

  // Get all subjects with their available class levels
  async getSubjectClassLevels() {
    await delay(150);
    
    const subjects = {};
    Object.keys(defaultIconsMap).forEach(subject => {
      subjects[subject] = Object.keys(defaultIconsMap[subject]);
    });
    
    return subjects;
  }
};